### ISSUE TITLE
User can see their car.

### ISSUE THREAD

**Issue by danielwrosenbaum** [danielwrosenbaum/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] ...
- [x] Create a basic HTML template 
- [x] Create a basic CSS template
- [x] Create a basic JS template
- [x] style page to look similar to template
- [x] add car to html
- [x] format car to fit on page correctly
- [x] position car at the starting line
