### ISSUE TITLE
User can turn their car.

### ISSUE THREAD

**Issue by danielwrosenbaum** [danielwrosenbaum/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] ...
- [x] create css classes for when race car is face up, down, left and right
- [x] query the dom for the race-car class to be edited
- [x] add event listeners on window for up, down, left and right
- [x] write function to respond to the appropriate key being hit
- [x] add transition so you can see car turn
