### ISSUE TITLE
User can start their car.

### ISSUE THREAD

**Issue by danielwrosenbaum** [danielwrosenbaum/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] ...
- [x] add listener event on window for when spacebar is hit
- [x] add css to push car around screen
- [x] make sure car doesn't go out of window
- [x] add interval timer to page
- [x] make interval timer respond to spacebar
