### ISSUE TITLE
User can stop their car.

### ISSUE THREAD

**Issue by danielwrosenbaum** [danielwrosenbaum/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] ...
- [x] add counter to code.
- [x] increment counter when spacebar is hit
- [x] add clearInterval
- [x] increment counter again after car stops
